# Use the base image for .NET 6
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Install dependencies for PDF generation
RUN apt-get update && apt-get install -y libgdiplus libc6-dev

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Template/Template.csproj", "Template/"]
RUN dotnet restore "./Template/Template.csproj"
COPY . .
WORKDIR "/src/Template"
RUN dotnet build "./Template.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Publish stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Template.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Final stage
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
# Set environment variable for Development mode
ENV ASPNETCORE_ENVIRONMENT=Development
ENTRYPOINT ["dotnet", "Template.dll"]
